### ISSUE TITLE
v4 Roadmap

### ISSUE THREAD

**Issue by octet-stream** [octet-stream/form-data#42]
I think it's time for me to start work on the next version of `formdata-node`. This version should be the last piece to make it fully spec-compatible. Here's what I want to do:

- [ ] Remove all additional APIs, keep only what is compatible with the spec. This change will not affect anyone who already dropped use of them;
- [ ] Remove builtin `multipart/form-data` encoder and rely on support of it in HTTP clients and [`form-data-encoder`](https://github.com/octet-stream/form-data-encoder) package;
- [ ] I should probably remove CJS support and focus on ESM, but I was thinking if it is not too early for that... My original plan was to drop it by the Node 12 EOL, so developers who depends on `formdata-node` have smoothen transitional period before they adopt ESM and I can focus on supporting only one major version of the package;
- [ ] If I decide to drop CJS, I will also need to get rid of the `File` class implementation in favour of the one provided by `fetch-blob`.
- [ ] Run tests against WPT maybe?

**Comment by jimmywarting** [comment]
I would say: go for ESM only, but first wait for web-stream-polyfill to reduce the package size. that 8MB was not so well received among others. Or don't go ESM just yet, some ppl actually preferred your CJS version over my ESM only package for that reason alone. 
both yours and mine will become a bit obsolete now when nodejs plans to ships File and FormData into core as well.

**Comment by octet-stream** [comment]
> Or don't go ESM just yet, some ppl actually preferred your CJS version over my ESM only package for that reason alone.

Yeah, because people still need CJS (I personally use it at leas for prototyping, because I want to use `ts-node-dev` which have no ESM support) I may keep it in v4. But technically, people can stick with v3, because v4 is more of a housekeeping release.

> both yours and mine will become a bit obsolete now when nodejs plans to ships File and FormData into core as well.

Yeah, the v4 would probably be the last version of my package at least for this reason.

**Comment by jimmywarting** [comment]
sad part is that you will be stuck with a older version of fetch-blob and be forced to use a own File Class as of now

**Comment by octet-stream** [comment]
Yeah, I'd prefer to update to v3, because it passes WPT.
