### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by octet-stream** [octet-stream/form-data#49]
I think it is time to keep a note for myself on what I gonna do for v5 and also make my plans clear for everyone who use this package.

Here's the list of what is going to change:

- [x] First of all, this package will be ESM only.
- [x] Entries in `FormData` constructor will be removed, because they are not spec-compatible. I should probably throw an error or somehow report that `formdata-node` doesn't support arguments in its constructor, or maybe just do what `undici` have in their [`FormData` implementation](https://github.com/nodejs/undici/blob/6c69c19624b5eea070d4eaa2d940644b7a252258/lib/fetch/formdata.js#L10-L14)
- [ ] Get rid of builtin `Blob` and `File` classes in favour of `fetch-blob`? I'm not sure about this one yet, [because `fetch-blob` adds `ReadableStream` onto `globalThis`](https://github.com/node-fetch/fetch-blob/blob/8ab587d34080de94140b54f07168451e7d0b655e/streams.cjs#L22) (they do seem to patch Blob object from Node.js too), which Node.js doesn't do as of now. I think I'd like to keep my package pure.
- [ ] Remove or deprecate builtin `fileFromPath` and `fileFromPathSync` in favour of the ones from `fetch-blob`.
- [x] Change type for `value` argument in `.append()` and `.set()` methods from `unknown` to `string | Blob`, to improve compatibility with [`@types/web`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/b0ff24cf46ccbfee230ee1601ce13705745317f6/inputfiles/overridingTypes.jsonc#L1133-L1146)

I will add more to this list if I find anything else I want to change.

**Comment by jimmywarting** [comment]
- I'm also throwing an error in my formdata constructor if argument len is > 1
- node's own blob now have `.stream()` and it's now considered as stabled and added onto the global namespace. maybe fetch-blob no longer needs to patch buffer.blob anymore... i bet that not many have even used `Buffer.Blob` in nodejs at all. it don't have any big usefulness yet if there isn't a way for filesystem to back them up.
- adding ReadableStream to globalThis might have been a side effect of what i have done... might reconsider it. hoping web-stream-polyfill will do something awesome with v4 and using builtin whatwg stream whenever possible and patching missing stuff onto it instead
